version: "3.7"
services:
  #############################################################################################
  ###                                 EFILING FRONTEND                                      ###
  #############################################################################################
  efiling-frontend:
    # need stdin_open:true because there is an issue with container being auto exited after startup with react-scripts 3.4.1
    stdin_open: true
    container_name: efiling-frontend
    build:
      context: ./src/frontend
      args:
        - SERVICE_NAME=efiling-frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - REACT_APP_KEYCLOAK_CLIENT_ID=efiling-frontend
      - REACT_APP_KEYCLOAK_URL=${KEYCLOAK_URL}
      - REACT_APP_API_BASE_URL=http://localhost:8080
      - REACT_APP_BAMBORA_REDIRECT_URL=http://localhost:3000/efiling

  #############################################################################################
  ###                                 EFILING DEMO                                          ###
  #############################################################################################
  efiling-demo:
    # need stdin_open:true because there is an issue with container being auto exited after startup with react-scripts 3.4.1
    stdin_open: true
    container_name: efiling-demo
    build:
      context: ./src/frontend
      args:
        - SERVICE_NAME=efiling-demo
    ports:
      - 3001:3000
    environment:
      - REACT_APP_KEYCLOAK_REALM=${EFILING_DEMO_KEYCLOAK_REALM}
      - REACT_APP_KEYCLOAK_CLIENT_ID=efiling-demo
      - REACT_APP_KEYCLOAK_URL=${EFILING_DEMO_KEYCLOAK_URL}
      - REACT_APP_API_BASE_URL=http://localhost:8080
      - REACT_APP_KEYCLOAK_CLIENT_SECRET=${EFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET}
      - REACT_APP_API_KEYCLOAK_URL=${KEYCLOAK_URL}
      - REACT_APP_DEMO_CLIENT_ID=demo-app

  #############################################################################################
  ###                           Efiling api backend app                                     ###
  #############################################################################################
  efiling-api:
    build:
      context: ./src/backend
      args:
        - SERVICE_NAME=efiling-api
        - MVN_PROFILE=${MVN_PROFILE:-demo}
        - SKIP_TESTS=true
        - STARTERS_V=v0.1.8
    ports:
      - "8080:8080"
    environment:
      - CSO_ACCOUNTFACADE_URI=${CSO_ACCOUNTFACADE_URI}
      - CSO_ACCOUNTFACADE_USERNAME=${CSO_ACCOUNTFACADE_USERNAME}
      - CSO_ACCOUNTFACADE_PASSWORD=${CSO_ACCOUNTFACADE_PASSWORD}
      - CSO_ROLEREGISTRY_USERNAME=${CSO_ROLEREGISTRY_USERNAME}
      - CSO_ROLEREGISTRY_PASSWORD=${CSO_ROLEREGISTRY_PASSWORD}
      - CSO_ROLEREGISTRY_URI=${CSO_ROLEREGISTRY_URI}
      - CSO_LOOKUPFACADE_USERNAME=${CSO_LOOKUPFACADE_USERNAME}
      - CSO_LOOKUPFACADE_PASSWORD=${CSO_LOOKUPFACADE_PASSWORD}
      - CSO_LOOKUPFACADE_URI=${CSO_LOOKUPFACADE_URI}
      - MVN_PROFILE=${MVN_PROFILE}
      - CSO_BCEIDSERVICE_URI=${CSO_BCEIDSERVICE_URI}
      - CSO_FILINGSTATSFACADE_URI=${CSO_FILINGSTATSFACADE_URI}
      - CSO_FILINGSTATSFACADE_USERNAME=${CSO_FILINGSTATSFACADE_USERNAME}
      - CSO_FILINGSTATSFACADE_PASSWORD=${CSO_FILINGSTATSFACADE_PASSWORD}
      - CSO_BCEIDSERVICE_USERNAME=${CSO_BCEIDSERVICE_USERNAME}
      - CSO_BCEIDSERVICE_PASSWORD=${CSO_BCEIDSERVICE_PASSWORD}
      - CSOWS_USERNAME=${CSOWS_USERNAME}
      - CSOWS_PASSWORD=${CSOWS_PASSWORD}
      - CSOWS_URI=${CSOWS_URI}
      - CSO_FILINGFACADE_URI=${CSO_FILINGFACADE_URI}
      - CSO_FILINGFACADE_PASSWORD=${CSO_FILINGFACADE_PASSWORD}
      - CSO_FILINGFACADE_USERNAME=${CSO_FILINGFACADE_USERNAME}
      - CSO_SERVICEFACADE_URI=${CSO_SERVICEFACADE_URI}
      - CSO_SERVICEFACADE_USERNAME=${CSO_SERVICEFACADE_USERNAME}
      - CSO_SERVICEFACADE_PASSWORD=${CSO_SERVICEFACADE_PASSWORD}
      - KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_RESOURCE=${KEYCLOAK_RESOURCE}
      - KEYCLOAK_CREDENTIALS_SECRET=${KEYCLOAK_CREDENTIALS_SECRET}
      - KEYCLOAK_SSL_REQUIRED=${KEYCLOAK_SSL_REQUIRED}
      - BAMBORA_APIPASSCODE=${BAMBORA_APIPASSCODE}
      - BAMBORA_MERCHANTID=${BAMBORA_MERCHANTID}
      - SFTP_KNOWNHOSTS=${SFTP_KNOWNHOSTS}
      - SFTP_REMOTELOCATION=${SFTP_REMOTELOCATION}
      - SFTP_PRIVATE_KEY=${SFTP_PRIVATE_KEY}
      - BCEID_SERVICE_URI=${BCEID_SERVICE_URI}
      - BCEID_SERVICE_USERNAME=${BCEID_SERVICE_USERNAME}
      - BCEID_SERVICE_PASSWORD=${BCEID_SERVICE_PASSWORD}
      - BCEID_SERVICE_ONLINE_SERVICE_ID=${BCEID_SERVICE_ONLINE_SERVICE_ID}
      - CSO_FILE_SERVER_HOST=${CSO_FILE_SERVER_HOST}
      - CSO_DEBUG_ENABLED=${CSO_DEBUG_ENABLED}
      - BAMBORA_PROFILE_URL=${BAMBORA_PROFILE_URL}
      - BAMBORA_HASHKEY=${BAMBORA_HASHKEY}
      - BAMBORA_PROFILE_SERVICE_VERSION=${BAMBORA_PROFILE_SERVICE_VERSION}
      - BAMBORA_URL_EXPIRY=10
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin
      - NAVIGATION_BASE_URL=http://localhost:3000/efiling
      - NAVIGATION_EXPIRYTIME=10
      - CLAMAV_HOST=clamav
      - CLAMAV_TIMEOUT=150000

    networks:
      - fisu-net

  #############################################################################################
  ###                                 REDIS SERVER                                          ###
  #############################################################################################
  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
    restart: always
    networks:
      - fisu-net

  #############################################################################################
  ###                                 REDIS COMMANDER                                       ###
  #############################################################################################
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=admin
    ports:
      - "8082:8081"
    networks:
      - fisu-net

  #############################################################################################
  ###                                        KEYCLOAK                                       ###
  #############################################################################################

  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_AUTH_SERVER_URL: http://localhost:8081/auth
      KEYCLOAK_REALM: SpringBootKeycloak
      KEYCLOAK_RESOURCE: efiling-api
      KEYCLOAK_CREDENTIALS_SECRET: 3d7be270-34a5-4c4f-82cb-d0d22cb88aa8
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      # JDBC_PARAMS: "ssl=true"
    volumes:
      - ./.settings/realm-export.json:/tmp/realm-export.json
    ports:
      - 8081:8080
    command: ["-Dkeycloak.profile.feature.upload_scripts=enabled"]
    networks:
      - fisu-net

  #############################################################################################
  ###                                        NGINX                                          ###
  #############################################################################################
  nginx:
    image: nginx:latest
    volumes:
      - .settings/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8083:80
    networks:
      - fisu-net

  #############################################################################################
  ###                             SFTP SERVER                                               ###
  #############################################################################################
  sftp:
    image: atmoz/sftp
    ports:
      - "23:22"
    command: admin:admin:::upload
    networks:
      - fisu-net

  #############################################################################################
  ###                             CLAMAV                                                    ###
  #############################################################################################
  clamav:
    image: mk0x/docker-clamav
    ports:
      - "3310:3310"
    networks:
      - fisu-net

  #############################################################################################
  ###                             APACHE REVERSE PROXY                                      ###
  #############################################################################################
  httpd:
    image: httpd:latest
    ports:
      - 80:80
      - 443:80
    networks:
      - fisu-net

volumes:
  data-redis:

networks:
  fisu-net:
    driver: "bridge"
